services:
    backblaze.b2:
        class: KamilZ\B2BackblazeBundle\Services\B2Client
        arguments: [%b2_backblaze%]

    backblaze.twig:
        class: KamilZ\B2BackblazeBundle\Twig\Extension\B2HelperExtension
        arguments: ["%b2_backblaze%"]
        public: false
        tags:
            - { name: twig.extension }